language: en

World_Blacklist:
#- world_nether
#- world_end

Item_Blacklist:
#- ENDER_DRAGON_SPAWN_EGG

# Taxes added when creating shops (in %) //CURRENTLY NOT WORKING!
Taxes: 0

# prevents Hoppers and Hopper Minecrads from stealing items from shops
Shop_hopper_protection: true